### Get User Count
GET http://localhost:3000/api/getUserCount

### Get Total Revenue
GET http://localhost:3000/api/getRevenue

### Create Admin
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "AdminUserName": "admin123111",
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "john.doe@example.com",
  "Password": "securepassword"
}


### Test Most Sold Products API

# Request to get the most sold products within a date range
GET http://localhost:3000/api/ProductCategoryWithMostOrders?startDate=2023-01-01&endDate=2023-12-31
Accept: application/json

### Test Most Sold Products API

# Request to get the most sold products within a date range
GET http://localhost:3000/api/ProductsWithMostNumberOfSales?startDate=2024-01-01&endDate=2024-12-31
Accept: application/json

###
