### Get User Count
GET http://localhost:3000/api/getUserCount

### Get Total Revenue
GET http://localhost:3000/api/getRevenue

### Create Admin
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "AdminUserName": "chamindu12",
  "FirstName": "Chamindu",
  "LastName": "Sathsara",
  "Email": "chamindusathsara27@gmail.com",
  "Password": "chamindu12"
}


